- name: Install dependencies
  composer:
    command: install
    working_dir: "{{ project_root }}"

- name: Check if site is already installed
  command: "cat {{ project_root}}/web/sites/default/settings.php"
  register: settings_php

- name: Install site
  command: "vendor/drupal/console/bin/drupal site:install --no-interaction --db-name=mcbalcaldi --db-user=mcbalcaldi --db-pass=\"{{ db_mcbalcaldi_password }}\" --langcode=es"
  args:
    chdir: "{{ project_root }}"
  when: settings_php.stdout.find('mcbalcaldi') == -1

- name: Config language UUID (for a bug workaround)
  command: vendor/drush/drush/drush config-set language.entity.es uuid 43f580b8-dc78-41cf-89ec-6f4e58f9fcaf -y
  args:
    chdir: "{{ project_root }}"

- name: Import configuration
  command: "vendor/drupal/console/bin/drupal config:import"
  args:
    chdir: "{{ project_root }}"

- name: Rebuild the cache
  command: "vendor/drupal/console/bin/drupal cache:rebuild"
  args:
    chdir: "{{ project_root }}"

- name: Configure web server
  block:
  - name: Load site configuration
    template:
      src: mcbalcaldi.conf.j2
      dest: /etc/apache2/sites-available/mcbalcaldi.conf
    notify: Restart web server

  - name: Enable site
    command: a2ensite mcbalcaldi
    notify: Restart web server
  become: yes
  become_user: root
