- name: Checkout the project from Git
  git:
    repo: 'ssh://git@github.com:pdacostaporto/mcbalcaldi.git'
    dest: "/var/www/mcbalcaldi"
    version: master
    accept_hostkey: yes
    ssh_opts: "-o StrictHostKeyChecking=no"
